/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ProfessionsRouteImport } from './routes/professions'
import { Route as MilitaryRanksRouteImport } from './routes/military-ranks'
import { Route as MapRouteImport } from './routes/map'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as FamiliesRouteImport } from './routes/families'
import { Route as DistinctionsRouteImport } from './routes/distinctions'
import { Route as DepotRouteImport } from './routes/depot'
import { Route as BansRouteImport } from './routes/bans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as ProfessionsIndexRouteImport } from './routes/professions.index'
import { Route as MilitaryRanksIndexRouteImport } from './routes/military-ranks.index'
import { Route as FamiliesIndexRouteImport } from './routes/families.index'
import { Route as DistinctionsIndexRouteImport } from './routes/distinctions.index'
import { Route as TreeIdRouteImport } from './routes/tree.$id'
import { Route as SourcesIdRouteImport } from './routes/sources.$id'
import { Route as ProfessionsIdRouteImport } from './routes/professions.$id'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as MilitaryRanksIdRouteImport } from './routes/military-ranks.$id'
import { Route as FamiliesIdRouteImport } from './routes/families.$id'
import { Route as DistinctionsIdRouteImport } from './routes/distinctions.$id'
import { Route as CommunesInseeRouteImport } from './routes/communes.$insee'
import { Route as RelationId1Id2RouteImport } from './routes/relation.$id1.$id2'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionsRoute = ProfessionsRouteImport.update({
  id: '/professions',
  path: '/professions',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitaryRanksRoute = MilitaryRanksRouteImport.update({
  id: '/military-ranks',
  path: '/military-ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesRoute = FamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => rootRouteImport,
} as any)
const DistinctionsRoute = DistinctionsRouteImport.update({
  id: '/distinctions',
  path: '/distinctions',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotRoute = DepotRouteImport.update({
  id: '/depot',
  path: '/depot',
  getParentRoute: () => rootRouteImport,
} as any)
const BansRoute = BansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourcesRoute,
} as any)
const ProfessionsIndexRoute = ProfessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionsRoute,
} as any)
const MilitaryRanksIndexRoute = MilitaryRanksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MilitaryRanksRoute,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamiliesRoute,
} as any)
const DistinctionsIndexRoute = DistinctionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DistinctionsRoute,
} as any)
const TreeIdRoute = TreeIdRouteImport.update({
  id: '/tree/$id',
  path: '/tree/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIdRoute = SourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SourcesRoute,
} as any)
const ProfessionsIdRoute = ProfessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfessionsRoute,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitaryRanksIdRoute = MilitaryRanksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MilitaryRanksRoute,
} as any)
const FamiliesIdRoute = FamiliesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FamiliesRoute,
} as any)
const DistinctionsIdRoute = DistinctionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DistinctionsRoute,
} as any)
const CommunesInseeRoute = CommunesInseeRouteImport.update({
  id: '/communes/$insee',
  path: '/communes/$insee',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationId1Id2Route = RelationId1Id2RouteImport.update({
  id: '/relation/$id1/$id2',
  path: '/relation/$id1/$id2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bans': typeof BansRoute
  '/depot': typeof DepotRoute
  '/distinctions': typeof DistinctionsRouteWithChildren
  '/families': typeof FamiliesRouteWithChildren
  '/gaps': typeof GapsRoute
  '/map': typeof MapRoute
  '/military-ranks': typeof MilitaryRanksRouteWithChildren
  '/professions': typeof ProfessionsRouteWithChildren
  '/sources': typeof SourcesRouteWithChildren
  '/stats': typeof StatsRoute
  '/communes/$insee': typeof CommunesInseeRoute
  '/distinctions/$id': typeof DistinctionsIdRoute
  '/families/$id': typeof FamiliesIdRoute
  '/military-ranks/$id': typeof MilitaryRanksIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/professions/$id': typeof ProfessionsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/tree/$id': typeof TreeIdRoute
  '/distinctions/': typeof DistinctionsIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/military-ranks/': typeof MilitaryRanksIndexRoute
  '/professions/': typeof ProfessionsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/relation/$id1/$id2': typeof RelationId1Id2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bans': typeof BansRoute
  '/depot': typeof DepotRoute
  '/gaps': typeof GapsRoute
  '/map': typeof MapRoute
  '/stats': typeof StatsRoute
  '/communes/$insee': typeof CommunesInseeRoute
  '/distinctions/$id': typeof DistinctionsIdRoute
  '/families/$id': typeof FamiliesIdRoute
  '/military-ranks/$id': typeof MilitaryRanksIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/professions/$id': typeof ProfessionsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/tree/$id': typeof TreeIdRoute
  '/distinctions': typeof DistinctionsIndexRoute
  '/families': typeof FamiliesIndexRoute
  '/military-ranks': typeof MilitaryRanksIndexRoute
  '/professions': typeof ProfessionsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/relation/$id1/$id2': typeof RelationId1Id2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bans': typeof BansRoute
  '/depot': typeof DepotRoute
  '/distinctions': typeof DistinctionsRouteWithChildren
  '/families': typeof FamiliesRouteWithChildren
  '/gaps': typeof GapsRoute
  '/map': typeof MapRoute
  '/military-ranks': typeof MilitaryRanksRouteWithChildren
  '/professions': typeof ProfessionsRouteWithChildren
  '/sources': typeof SourcesRouteWithChildren
  '/stats': typeof StatsRoute
  '/communes/$insee': typeof CommunesInseeRoute
  '/distinctions/$id': typeof DistinctionsIdRoute
  '/families/$id': typeof FamiliesIdRoute
  '/military-ranks/$id': typeof MilitaryRanksIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/places/$id': typeof PlacesIdRoute
  '/professions/$id': typeof ProfessionsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/tree/$id': typeof TreeIdRoute
  '/distinctions/': typeof DistinctionsIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/military-ranks/': typeof MilitaryRanksIndexRoute
  '/professions/': typeof ProfessionsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/relation/$id1/$id2': typeof RelationId1Id2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bans'
    | '/depot'
    | '/distinctions'
    | '/families'
    | '/gaps'
    | '/map'
    | '/military-ranks'
    | '/professions'
    | '/sources'
    | '/stats'
    | '/communes/$insee'
    | '/distinctions/$id'
    | '/families/$id'
    | '/military-ranks/$id'
    | '/people/$id'
    | '/places/$id'
    | '/professions/$id'
    | '/sources/$id'
    | '/tree/$id'
    | '/distinctions/'
    | '/families/'
    | '/military-ranks/'
    | '/professions/'
    | '/sources/'
    | '/relation/$id1/$id2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bans'
    | '/depot'
    | '/gaps'
    | '/map'
    | '/stats'
    | '/communes/$insee'
    | '/distinctions/$id'
    | '/families/$id'
    | '/military-ranks/$id'
    | '/people/$id'
    | '/places/$id'
    | '/professions/$id'
    | '/sources/$id'
    | '/tree/$id'
    | '/distinctions'
    | '/families'
    | '/military-ranks'
    | '/professions'
    | '/sources'
    | '/relation/$id1/$id2'
  id:
    | '__root__'
    | '/'
    | '/bans'
    | '/depot'
    | '/distinctions'
    | '/families'
    | '/gaps'
    | '/map'
    | '/military-ranks'
    | '/professions'
    | '/sources'
    | '/stats'
    | '/communes/$insee'
    | '/distinctions/$id'
    | '/families/$id'
    | '/military-ranks/$id'
    | '/people/$id'
    | '/places/$id'
    | '/professions/$id'
    | '/sources/$id'
    | '/tree/$id'
    | '/distinctions/'
    | '/families/'
    | '/military-ranks/'
    | '/professions/'
    | '/sources/'
    | '/relation/$id1/$id2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BansRoute: typeof BansRoute
  DepotRoute: typeof DepotRoute
  DistinctionsRoute: typeof DistinctionsRouteWithChildren
  FamiliesRoute: typeof FamiliesRouteWithChildren
  GapsRoute: typeof GapsRoute
  MapRoute: typeof MapRoute
  MilitaryRanksRoute: typeof MilitaryRanksRouteWithChildren
  ProfessionsRoute: typeof ProfessionsRouteWithChildren
  SourcesRoute: typeof SourcesRouteWithChildren
  StatsRoute: typeof StatsRoute
  CommunesInseeRoute: typeof CommunesInseeRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PlacesIdRoute: typeof PlacesIdRoute
  TreeIdRoute: typeof TreeIdRoute
  RelationId1Id2Route: typeof RelationId1Id2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professions': {
      id: '/professions'
      path: '/professions'
      fullPath: '/professions'
      preLoaderRoute: typeof ProfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/military-ranks': {
      id: '/military-ranks'
      path: '/military-ranks'
      fullPath: '/military-ranks'
      preLoaderRoute: typeof MilitaryRanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families': {
      id: '/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof FamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distinctions': {
      id: '/distinctions'
      path: '/distinctions'
      fullPath: '/distinctions'
      preLoaderRoute: typeof DistinctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depot': {
      id: '/depot'
      path: '/depot'
      fullPath: '/depot'
      preLoaderRoute: typeof DepotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bans': {
      id: '/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof BansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/professions/': {
      id: '/professions/'
      path: '/'
      fullPath: '/professions/'
      preLoaderRoute: typeof ProfessionsIndexRouteImport
      parentRoute: typeof ProfessionsRoute
    }
    '/military-ranks/': {
      id: '/military-ranks/'
      path: '/'
      fullPath: '/military-ranks/'
      preLoaderRoute: typeof MilitaryRanksIndexRouteImport
      parentRoute: typeof MilitaryRanksRoute
    }
    '/families/': {
      id: '/families/'
      path: '/'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof FamiliesRoute
    }
    '/distinctions/': {
      id: '/distinctions/'
      path: '/'
      fullPath: '/distinctions/'
      preLoaderRoute: typeof DistinctionsIndexRouteImport
      parentRoute: typeof DistinctionsRoute
    }
    '/tree/$id': {
      id: '/tree/$id'
      path: '/tree/$id'
      fullPath: '/tree/$id'
      preLoaderRoute: typeof TreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$id': {
      id: '/sources/$id'
      path: '/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof SourcesIdRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/professions/$id': {
      id: '/professions/$id'
      path: '/$id'
      fullPath: '/professions/$id'
      preLoaderRoute: typeof ProfessionsIdRouteImport
      parentRoute: typeof ProfessionsRoute
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/places/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/military-ranks/$id': {
      id: '/military-ranks/$id'
      path: '/$id'
      fullPath: '/military-ranks/$id'
      preLoaderRoute: typeof MilitaryRanksIdRouteImport
      parentRoute: typeof MilitaryRanksRoute
    }
    '/families/$id': {
      id: '/families/$id'
      path: '/$id'
      fullPath: '/families/$id'
      preLoaderRoute: typeof FamiliesIdRouteImport
      parentRoute: typeof FamiliesRoute
    }
    '/distinctions/$id': {
      id: '/distinctions/$id'
      path: '/$id'
      fullPath: '/distinctions/$id'
      preLoaderRoute: typeof DistinctionsIdRouteImport
      parentRoute: typeof DistinctionsRoute
    }
    '/communes/$insee': {
      id: '/communes/$insee'
      path: '/communes/$insee'
      fullPath: '/communes/$insee'
      preLoaderRoute: typeof CommunesInseeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relation/$id1/$id2': {
      id: '/relation/$id1/$id2'
      path: '/relation/$id1/$id2'
      fullPath: '/relation/$id1/$id2'
      preLoaderRoute: typeof RelationId1Id2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DistinctionsRouteChildren {
  DistinctionsIdRoute: typeof DistinctionsIdRoute
  DistinctionsIndexRoute: typeof DistinctionsIndexRoute
}

const DistinctionsRouteChildren: DistinctionsRouteChildren = {
  DistinctionsIdRoute: DistinctionsIdRoute,
  DistinctionsIndexRoute: DistinctionsIndexRoute,
}

const DistinctionsRouteWithChildren = DistinctionsRoute._addFileChildren(
  DistinctionsRouteChildren,
)

interface FamiliesRouteChildren {
  FamiliesIdRoute: typeof FamiliesIdRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
}

const FamiliesRouteChildren: FamiliesRouteChildren = {
  FamiliesIdRoute: FamiliesIdRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
}

const FamiliesRouteWithChildren = FamiliesRoute._addFileChildren(
  FamiliesRouteChildren,
)

interface MilitaryRanksRouteChildren {
  MilitaryRanksIdRoute: typeof MilitaryRanksIdRoute
  MilitaryRanksIndexRoute: typeof MilitaryRanksIndexRoute
}

const MilitaryRanksRouteChildren: MilitaryRanksRouteChildren = {
  MilitaryRanksIdRoute: MilitaryRanksIdRoute,
  MilitaryRanksIndexRoute: MilitaryRanksIndexRoute,
}

const MilitaryRanksRouteWithChildren = MilitaryRanksRoute._addFileChildren(
  MilitaryRanksRouteChildren,
)

interface ProfessionsRouteChildren {
  ProfessionsIdRoute: typeof ProfessionsIdRoute
  ProfessionsIndexRoute: typeof ProfessionsIndexRoute
}

const ProfessionsRouteChildren: ProfessionsRouteChildren = {
  ProfessionsIdRoute: ProfessionsIdRoute,
  ProfessionsIndexRoute: ProfessionsIndexRoute,
}

const ProfessionsRouteWithChildren = ProfessionsRoute._addFileChildren(
  ProfessionsRouteChildren,
)

interface SourcesRouteChildren {
  SourcesIdRoute: typeof SourcesIdRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesIdRoute: SourcesIdRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BansRoute: BansRoute,
  DepotRoute: DepotRoute,
  DistinctionsRoute: DistinctionsRouteWithChildren,
  FamiliesRoute: FamiliesRouteWithChildren,
  GapsRoute: GapsRoute,
  MapRoute: MapRoute,
  MilitaryRanksRoute: MilitaryRanksRouteWithChildren,
  ProfessionsRoute: ProfessionsRouteWithChildren,
  SourcesRoute: SourcesRouteWithChildren,
  StatsRoute: StatsRoute,
  CommunesInseeRoute: CommunesInseeRoute,
  PeopleIdRoute: PeopleIdRoute,
  PlacesIdRoute: PlacesIdRoute,
  TreeIdRoute: TreeIdRoute,
  RelationId1Id2Route: RelationId1Id2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
